### ISSUE TITLE
Accept CKAN package_search params as arguments

### ISSUE THREAD

**Issue by seanh** [ckan/ckanapi-exporter#1]
Export only matching datasets, not all

**Comment by camfindlay** [comment]
+1

**Comment by camfindlay** [comment]
Looking to address this in #3

**Comment by camfindlay** [comment]
Solved in #3 this can be closed.

**Comment by camfindlay** [comment]
bump - would be great to get a 0.1.0 tagged version after this feature change and a new release on pypi... been nearly a year maintainers! ;)
